version: '3'
services:
  # client:
  #   image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
  #   volumes:
  #     # Mount the root folder that contains .git
  #     - .:/workspace:cached
  #   command: sleep infinity
  #   links:
  #     - api

  api:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity